language: java
services:
  - docker
sudo: required
branches:
  only:
    - master
script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - docker build . -t "mikeyboom/pmsocspscs:latest"
before_install:
  - openssl aes-256-cbc -K $encrypted_1687bb340939_key -iv $encrypted_1687bb340939_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host $SERVER_IP\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
  - docker login -u=$DOCKER_NAME -p="$DOKCER_PWD"
  - docker push mikeyboom/pmsocspscs:latest
  - chmod 600 ~/.ssh/id_rsa
#  - ssh -o "StrictHostKeyChecking no" -i id_rsa root@$SERVER_IP "rm -rf pmsocspscs;git clone https:github.com/mikeygithub/pmsocspscs.git;cd pmsocspscs;chmod +x run.sh; ./run.sh;exit"
