global:
  smtp_smarthost: 'smtp.163.com:25'
  smtp_from: '18276297824@163.com'
  smtp_auth_username: '18276297824@163.com'
  smtp_auth_password: 'goyb578247520'
  smtp_require_tls: false

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10m
  receiver: live-monitoring

receivers:
  - name: 'live-monitoring'
    email_configs:
      - to: 'biaogejiushibiao@outlook.com'
