version: '3.7'
networks:
  monitor:
    driver: bridge

services:
#  pmsocspscs:
#    image: mikeyboom/pmsocspscs
#    ports:
#      - "8081:8081"
#    environment:
#      - spring.profiles.active=pro
#    networks:
#      - monitor
#################################################################################################
#  prometheus:
#    image: prom/prometheus
#    container_name: prometheus
#    hostname: prometheus
#    restart: always
#    volumes:
#      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
#      - ./monitoring/node_down.yml:/etc/prometheus/node_down.yml
#    ports:
#      - "9090:9090"
#    networks:
#      - monitor
#
#  alertmanager:
#    image: prom/alertmanager
#    container_name: alertmanager
#    hostname: alertmanager
#    restart: always
#    volumes:
#      - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml
#    ports:
#      - "9093:9093"
#    networks:
#      - monitor
#  grafana:
#    image: grafana/grafana
#    container_name: grafana
#    hostname: grafana
#    restart: always
#    ports:
#      - "3000:3000"
#    networks:
#      - monitor
#  node-exporter:
#    image: quay.io/prometheus/node-exporter
#    container_name: node-exporter
#    hostname: node-exporter
#    restart: always
#    ports:
#      - "9100:9100"
#    networks:
#      - monitor
#  cadvisor:
#    image: google/cadvisor
#    container_name: cadvisor
#    hostname: cadvisor
#    restart: always
#    volumes:
#      - /:/rootfs:ro
#      - /var/run:/var/run:rw
#      - /sys:/sys:ro
#      - /var/lib/docker/:/var/lib/docker:ro
#    ports:
#      - "8080:8080"
#    networks:
#      - monitor
#################################################################################################
#  redis:
#    image: redis:latest
#    ports:
#      - "6379:6379"
#    networks:
#      - monitor
################################################################################################
  mysql_master:
    image: mysql:5.7
    env_file:
      - ./cluster/master/mysql_master.env
    container_name: "mysql_master"
    restart: "no"
    ports:
      - 4406:3306
    volumes:
      - ./cluster/master/conf/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./cluster/master/data:/var/lib/mysql
      - ./cluster/databases/:/tmp/sql/
    command:
      mysql -h localhost -P3306 -uroot -p123456 pmsocspsc < /tmp/sql/pmsocspsc.sql
    networks:
      - monitor

  mysql_slave1:
    image: mysql:5.7
    env_file:
      - cluster/slave1/mysql_slave.env
    container_name: "mysql_slave-1"
    restart: "no"
    ports:
      - 5506:3306
    depends_on:
      - mysql_master
    volumes:
      - ./cluster/slave1/conf/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./cluster/slave1/data:/var/lib/mysql
    networks:
      - monitor

  mysql_slave2:
    image: mysql:5.7
    env_file:
      - ./cluster/slave2/mysql_slave.env
    container_name: "mysql_slave-2"
    restart: "no"
    ports:
      - 5507:3306
    depends_on:
      - mysql_master
    volumes:
      - ./cluster/slave2/conf/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./cluster/slave2/data:/var/lib/mysql
    networks:
      - monitor