global:
  scrape_interval:     15s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['47.106.210.183:9093']
rule_files:
  - "node_down.yml"
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['47.106.210.183:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['47.106.210.183:8080']

  - job_name: 'node-exporter'
    scrape_interval: 8s
    static_configs:
      - targets: ['47.106.210.183:9100']
